### ISSUE TITLE
segmentation fault. Why ?

### ISSUE THREAD

**Issue by rafathefull** [tuffnatty/hbgi#10]
Hi, sometines, random, show this error;
./sourceview_s
Unrecoverable error 6005: Exception SIGSEGV at address 0x1011b88

**Comment by rafathefull** [comment]
Hi.. Investigation in send possible problem in function **hbgobject_pointer_register_types**
Please , can you confirm this problem ?

 demo git:(master) ✗ gdb navigator_s                         
This GDB was configured as "x86_64-linux-gnu".
(gdb) run
Starting program: /home/rafa/hbgi/demo/navigator_s 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000006549c8 in ?? ()
(gdb) backtrace 
#0  0x00000000006549c8 in ?? ()
#1  0x00007ffff79ed230 in hb_gcRefFree () from /usr/local/lib/libharbour.so.3.4
#2  0x00007ffff79ed350 in hb_itemRelease () from /usr/local/lib/libharbour.so.3.4
#3  0x0000000000413239 in **hbgobject_pointer_register_types** ()
    at ../../home/rafa/hbgi/gobject/hbgpointer.c:209
#4  0x0000000000412fb9 in hbgobject_init (dummy=0x0) at ../../home/rafa/hbgi/gobject/hbgobject.c:2308
#5  0x00007ffff7a29fd9 in hb_vmInit () from /usr/local/lib/libharbour.so.3.4
#6  0x00007ffff7829183 in main () from /usr/local/lib/libharbour.so.3.4
#7  0x00007ffff6bfbf45 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x0000000000406cb5 in _start ()
(gdb) Quit
